### ISSUE TITLE
Use a single namespace for EMMO top and middle

### ISSUE THREAD

**Issue by jesper-friis** [emmo-repo/EMMO#125]
The reason that EMMO is divided into several modules is to organise the ontology into topical related concepts, not impose namespaces. 

All names and skos:prefLabels are required to be unique within EMMO top and middle. Hence, there are no need for namespacing within EMMO top and middle. As suggested by Matthias, using a single namespace will make it simpler to move entities between modules and thereby simplify maintainance. 

If we go for this, remember to document it in the governance document.

**Comment by emanueleghedini** [comment]
Done in 1.0.0-beta
