### ISSUE TITLE
Scientific notation not supported with xsd:decimal

### ISSUE THREAD

**Issue by quaat** [emmo-repo/EMMO#131]
AllegroGraph was not able to import EMMO because siunits.owl use xsd:decimal, which does not support scientific notation.
Changed xsd:decimal to xsd:float in the file and imported the ontology successfully into the triplestore.

See https://github.com/quaat/EMMO/blob/master/middle/siunits.owl

**Comment by jesper-friis** [comment]
All use of xsd:decimal has been replaced with xsd:double in upstream 1.0.0-beta. Thanks
