### ISSUE TITLE
Fix redirections

### ISSUE THREAD

**Issue by jesper-friis** [emmo-repo/EMMO#132]
Example:
http://emmo.info/emmo/1.0.0-beta/top is supposed to be redirected to https://github.com/emmo-repo/EMMO/raw/1.0.0-beta/top/top.owl but unfortunately it is redirected to https://github.com/emmo-repo/EMMO/raw/1.0.0-beta/emmo.owl which is the top-level EMMO itself.

The same is the case for all other modules.

**Comment by emanueleghedini** [comment]
Fixed in the emmo.info server .htacces file
