### ISSUE TITLE
error when importing to protégé

### ISSUE THREAD

**Issue by luisenriqueramos1977** [emmo-repo/EMMO#144]
Dear friends, 

I am trying to import commonmaterials.owl into protégé, and obtain an error:

org.semanticweb.owlapi.rdf.rdfxml.parser.RDFParserException: [line=8:column=41] Expecting rdf:RDF element.

this ontology should open in protégé 5.0?

Luis Ramos

**Comment by jesper-friis** [comment]
Dear Luis,
domain/commonmaterials.ttl opens fine for me in Protege in the upstream 1.0.0-beta branch. Note that we have switched from rdf/xml to turtle format. 

Please let us know if that branch works for you so we can close the issue.

**Comment by jesper-friis** [comment]
By the way, ordinal was added to the catalog file in commit f6f52a042. Without that the ordinal will not load correctly when opening commonmaterials.ttl in protege

**Comment by jesper-friis** [comment]
Closing this issue
