### ISSUE TITLE
Add EngineeredParts (if not already on schedule for next release)

### ISSUE THREAD

**Issue by SimonStier** [emmo-repo/EMMO#147]
@jesper-friis Participant/Engineered contains Material and Device, but nothing like EngineeredParts, consisting of subparts and finally material. EngineeredParts would be Participants in Process/../DescreteManufacturing. As discussed, EngineeredParts may subclass Physicalistic/Matter/Continuum

**Comment by jesper-friis** [comment]
Sorry for this very late answer. The holistic perspective in upcoming EMMO 1.0.0-beta2 has now a rather comprehensive description of a whole and its parts/roles that can be used to describe these cases.
