### ISSUE TITLE
Add ObjectProperties "hasSuccessor" and "hasPredecessor" (if not already on schedule for next release)

### ISSUE THREAD

**Issue by SimonStier** [emmo-repo/EMMO#148]
@jesper-friis  As discussed, hasSuccessor/hasPredecessor or equivalents could be added as subproperties of mereotopolocigal/connected/hasContactWith

**Comment by jesper-friis** [comment]
EMMO 1.0.0-beta2 has now the `isTimeContactWith` relation which I guess has the same semantics as `hasPredecessor`. `hasSuccessor` is simply its inverse.
