### ISSUE TITLE
Add ObjectProperties "hasInput" and "hasOutput"

### ISSUE THREAD

**Issue by SimonStier** [emmo-repo/EMMO#149]
@jesper-friis hasInput/hasEduct and hasOutput/hasProduct are necessary to model flow within a process and could be added as subproperties of mereotopolocigal/connected/hasPart/hasParticipant

**Comment by jesper-friis** [comment]
Hi Simon. Thanks for the suggestion and sorry for late response. `hasProcessInput`/`hasProcessOutput` have now been included in the upstream 1.0.0-beta2 branch and will be come part of the next release. There are no `hasProduct`, but `hasProcessOutput` may be used instead, like in `Manufacturing hasProcessOutput some Product`. 

There are no `hasEduct`. This is very specific and should probably belong to a chemistry domain ontology.
