### ISSUE TITLE
Unconnected ontology elements

### ISSUE THREAD

**Issue by jesper-friis** [emmo-repo/EMMO#16]
From running OntOlogy Pitfall skanner! (OOPS!) on http://oops.linkeddata.es/

Results for P04: Creating unconnected ontology elements.7 cases | Minor

Ontology elements (classes, object properties and datatype properties) are created isolated, with no relation to the rest of the ontology.

• This pitfall appears in the following elements:
› http://emmo.info/domains/emmo-material.owl#EMMO_7db59e56_f68b_48b7_ae99_891c35ae5c3b
› http://emmo.info/domains/emmo-material.owl#EMMO_eb3c61f0_3983_4346_a0c6_e7f6b90a67a8
› http://emmo.info/domains/emmo-material.owl#EMMO_4588526f_8553_4f4d_aa73_a483e88d599b
› http://emmo.info/domains/emmo-properties.owl#EMMO_2a888cdf_ec4a_4ec5_af1c_0343372fc978
› http://emmo.info/domains/emmo-material.owl#EMMO_25f8b804_9a0b_4387_a3e7_b35bce5365ee
› http://emmo.info/domains/emmo-properties.owl#EMMO_251cfb4f_5c75_4778_91ed_6c8395212fd8
› http://emmo.info/domains/emmo-material.owl#EMMO_db03061b_db31_4132_a47a_6a634846578b

**Comment by jesper-friis** [comment]
This seems not to be a problem in EMMO, but rather that OOPS! does not recognises classes that are listed with owl:disjointUnionOf as connected.

**Comment by nanodome** [comment]
> This seems not to be a problem in EMMO, but rather that OOPS! does not recognises classes that are listed with owl:disjointUnionOf as connected.

Yep! The use of disjoint union statements is done in order to reduce the number of axioms in the EMMO, leaving the reasoner to infer the hierarchical structure. 

Everytime is possible I would prefer to write the EMMO without imposing a taxonomy, but making it emerge by relations.
