### ISSUE TITLE
Missing annotations

### ISSUE THREAD

**Issue by jesper-friis** [emmo-repo/EMMO#17]
From running OntOlogy Pitfall skanner! (OOPS!) on http://oops.linkeddata.es/

Results for P08: Missing annotations.87 cases | Minor

This pitfall consists in creating an ontology element and failing to provide human readable annotations attached to it. Consequently, ontology elements lack annotation properties that label them (e.g. rdfs:label, lemon:LexicalEntry, skos:prefLabel or skos:altLabel) or that define them (e.g. rdfs:comment or dc:description). This pitfall is related to the guidelines provided in [5].

[5] Vrandecic, D. (2010). Ontology Evaluation. PhD thesis. 

• The following elements have neither rdfs:comment or skos:definition defined:
› http://emmo.info/domains/emmo-models.owl#EMMO_4456a5d2_16a6_4ee1_9a8e_5c75956b28ea
› http://emmo.info/domains/emmo-models.owl#EMMO_53935db0_af45_4426_b9e9_244a0d77db00
› http://emmo.info/domains/emmo-models.owl#EMMO_22522299_4091_4d1f_82a2_3890492df6db
› http://emmo.info/domains/emmo-models.owl#EMMO_9c32fd69_f480_4130_83b3_fb25d9face14
› http://emmo.info/domains/emmo-models.owl#EMMO_f7ed665b_c2e1_42bc_889b_6b42ed3a36f0
› http://emmo.info/domains/emmo-models.owl#EMMO_b29fd350_39aa_4af7_9459_3faa0544cba6
› http://emmo.info/domains/emmo-models.owl#EMMO_f19ff3b4_6bfe_4c41_a2b2_9affd39c140b
› http://emmo.info/domains/emmo-models.owl#EMMO_6eca09be_17e9_445e_abc9_000aa61b7a11
› http://emmo.info/domains/emmo-models.owl#EMMO_314d0bd5_67ed_437e_a609_36d46147cea7
› http://emmo.info/domains/emmo-models.owl#EMMO_db9a009e_f097_43f5_9520_6cbc07e7610b
› http://emmo.info/domains/emmo-models.owl#EMMO_a4b14b83_9392_4a5f_a2e8_b2b58793f59b
› http://emmo.info/domains/emmo-models.owl#EMMO_6c739b1a_a774_4416_bb31_1961486fa9ed
› http://emmo.info/domains/emmo-models.owl#EMMO_84cadc45_6758_46f2_ba2a_5ead65c70213
› http://emmo.info/domains/emmo-material.owl#EMMO_df808271_df91_4f27_ba59_fa423c51896c
› http://emmo.info/domains/emmo-material.owl#EMMO_5b2222df_4da6_442f_8244_96e9e45887d1
› http://emmo.info/domains/emmo-material.owl#EMMO_50781fd9_a9e4_46ad_b7be_4500371d188d
› http://emmo.info/domains/emmo-material.owl#EMMO_eb3c61f0_3983_4346_a0c6_e7f6b90a67a8
› http://emmo.info/domains/emmo-material.owl#EMMO_174cf221_9d16_427c_abea_e217a948969b
› http://emmo.info/domains/emmo-material.owl#EMMO_1067b97a_84f8_4d22_8ace_b842b8ce355c
› http://emmo.info/domains/emmo-material.owl#EMMO_87ac88ff_8379_4f5a_8c7b_424a8fff1ee8
› http://emmo.info/domains/emmo-material.owl#EMMO_70dac51e_bddd_48c2_8a98_7d8395e91fc2
› http://emmo.info/domains/emmo-material.owl#EMMO_f835f4d4_c665_403d_ab25_dca5cc74be52
› http://emmo.info/domains/emmo-material.owl#EMMO_e5488299_8dab_4ebb_900a_26d2abed8396
› http://emmo.info/domains/emmo-material.owl#EMMO_25f8b804_9a0b_4387_a3e7_b35bce5365ee
› http://emmo.info/domains/emmo-material.owl#EMMO_7d66bde4_b68d_41cc_b5fc_6fd98c5e2ff0
› http://emmo.info/domains/emmo-material.owl#EMMO_8f87e700_99a8_4427_8ffb_e493de05c217
› http://emmo.info/domains/emmo-material.owl#EMMO_8043d3c6_a4c1_4089_ba34_9744e28e5b3d
› http://emmo.info/domains/emmo-material.owl#EMMO_3c218fbe_60c9_4597_8bcf_41eb1773af1f
› http://emmo.info/domains/emmo-material.owl#EMMO_5c4aff3c_c30c_4507_86d5_b4df41eb9f2f
› http://emmo.info/domains/emmo-material.owl#EMMO_a2b006f2_bbfd_4dba_bcaa_3fca20cd6be1
› http://emmo.info/domains/emmo-material.owl#EMMO_7db59e56_f68b_48b7_ae99_891c35ae5c3b
› http://emmo.info/domains/emmo-material.owl#EMMO_385b8f6e_43ac_4596_ad76_ac322c68b7ca
› http://emmo.info/domains/emmo-material.owl#EMMO_72d53756_7fb1_46ed_980f_83f47efbe105
› http://emmo.info/domains/emmo-material.owl#EMMO_4588526f_8553_4f4d_aa73_a483e88d599b
› http://emmo.info/domains/emmo-math.owl#EMMO_fe7e56ce_118b_4243_9aad_20eb9f4f31f6
› http://emmo.info/domains/emmo-math.owl#EMMO_1a663927_3b68_4618_acd3_a8aa0d406329
› http://emmo.info/domains/emmo-math.owl#EMMO_031d61af_6405_41de_8880_df2f85a53383
› http://emmo.info/domains/emmo-physical-properties.owl#EMMO_f2d5d3ad_2e00_417f_8849_686f3988d929
› http://emmo.info/domains/emmo-physical-properties.owl#EMMO_dd4a7f3e_ef56_466c_ac1a_d2716b5f87ec
› http://emmo.info/domains/emmo-physical-properties.owl#EMMO_c46f091c_0420_4c1a_af30_0a2c8ebcf7d7
› http://emmo.info/domains/emmo-physical-properties.owl#EMMO_b081b346_7279_46ef_9a3d_2c088fcd79f4
› http://emmo.info/domains/emmo-physical-properties.owl#EMMO_909415d1_7c43_4d5e_bbeb_7e1910159f66
› http://emmo.info/domains/emmo-physical-properties.owl#EMMO_463bcfda_867b_41d9_a967_211d4d437cfb
› http://emmo.info/domains/emmo-geometry.owl#EMMO_0ef4ff4a_5458_4f2a_b51f_4689d472a3f2
› http://emmo.info/domains/emmo-geometry.owl#EMMO_46f0f8df_4dc6_418f_8036_10427a3a288e
› http://emmo.info/domains/emmo-geometry.owl#EMMO_25f5ca8e_8f7f_44d8_a392_bd3fe8894458
› http://emmo.info/domains/emmo-geometry.owl#EMMO_9268958f_7f54_48ab_a693_febe2645892b
› http://emmo.info/domains/emmo-geometry.owl#EMMO_0c576e13_4ee7_4f3d_bfe9_1614243df018
› http://emmo.info/domains/emmo-geometry.owl#EMMO_d7bf784a_db94_4dd9_861c_54f262846fbf
› http://emmo.info/domains/emmo-geometry.owl#EMMO_0ab0485c_9e5b_4257_a679_90a2dfba5c7c
› http://emmo.info/domains/emmo-geometry.owl#EMMO_5f278af9_8593_4e27_a717_ccc9e07a0ddf
› http://emmo.info/domains/emmo-geometry.owl#EMMO_86060335_31c2_4820_b433_27c64aea0366
› http://emmo.info/domains/emmo-geometry.owl#EMMO_b2a234a8_579a_422c_9305_b8f7e72c76cd
› http://emmo.info/domains/emmo-geometry.owl#EMMO_39362460_2a97_4367_8f93_0418c2ac9a08
› http://emmo.info/domains/emmo-geometry.owl#EMMO_3e309118_e8b7_4021_80f4_642d2df65d94
› http://emmo.info/domains/emmo-usercase.owl#EMMO_e775e341_5687_4d45_b50c_379b098a8c26
› http://emmo.info/domains/emmo-usercase.owl#EMMO_494b372c_cfdf_47d3_a4de_5e037c540de8
› http://emmo.info/perspectives/emmo-semiotics.owl#EMMO_008fd3b2_4013_451f_8827_52bceab11841
› http://emmo.info/perspectives/emmo-semiotics.owl#EMMO_0527413c_b286_4e9c_b2d0_03fb2a038dee
› http://emmo.info/perspectives/emmo-semiotics.owl#EMMO_0cd58641_824c_4851_907f_f4c3be76630c
› http://emmo.info/perspectives/emmo-semiotics.owl#EMMO_054af807_85cd_4a13_8eba_119dfdaaf38b
› http://emmo.info/domains/emmo-properties.owl#EMMO_1b52ee70_121e_4d8d_8419_3f97cd0bd89c
› http://emmo.info/domains/emmo-properties.owl#EMMO_10a5fd39_06aa_4648_9e70_f962a9cb2069
› http://emmo.info/perspectives/emmo-processual.owl#EMMO_0277f24a_ea7f_4917_81b7_fb0406c8fc62
› http://emmo.info/domains/emmo-models.owl#EMMO_24c71baf_6db6_48b9_86c8_8c70cf36db0c
› http://emmo.info/domains/emmo-math.owl#EMMO_3446e167_c576_49d6_846c_215bb8878a55
› http://emmo.info/perspectives/emmo-existent.owl#EMMO_b2282816_b7a3_44c6_b2cb_3feff1ceb7fe
› http://emmo.info/perspectives/emmo-existent.owl#EMMO_a50d920d_1ee3_4668_9a73_5d80a1c6fe15
› http://emmo.info/perspectives/emmo-existent.owl#EMMO_65a2c5b8_e4d8_4a51_b2f8_e55effc0547d
› http://emmo.info/perspectives/emmo-semiotics.owl#EMMO_eb3518bf_f799_4f9e_8c3e_ce59af11453b
› http://emmo.info/perspectives/emmo-semiotics.owl#EMMO_60577dea_9019_4537_ac41_80b0fb563d41
› http://emmo.info/perspectives/emmo-semiotics.owl#EMMO_39c3815d_8cae_4c8f_b2ff_eeba24bec455
› http://emmo.info/perspectives/emmo-semiotics.owl#EMMO_297999d6_c9e4_4262_9536_bd524d1c6e21
› http://emmo.info/perspectives/emmo-semiotics.owl#EMMO_2337e25c_3c60_43fc_a8f9_b11a3f974291
› http://emmo.info/domains/emmo-properties.owl#EMMO_e1097637_70d2_4895_973f_2396f04fa204
› http://emmo.info/perspectives/emmo-processual.owl#EMMO_c5aae418_1622_4d02_93c5_21159e28e6c1
› http://emmo.info/base/emmo-mereotopology.owl#EMMO_7afbed84_7593_4a23_bd88_9d9c6b04e8f6
› http://emmo.info/base/emmo-4d.owl#EMMO_f68030be_94b8_4c61_a161_886468558054
› http://emmo.info/base/emmo-4d.owl#EMMO_6e046dd0_9634_4013_b2b1_9cc468087c83
› http://emmo.info/base/emmo-mereotopology.owl#EMMO_4d6504f1_c470_4ce9_b941_bbbebc9ab05d
› http://emmo.info/base/emmo-mereotopology.owl#EMMO_d893d373_b579_4867_841e_1c2b31a8d2c6
› http://emmo.info/base/emmo-mereotopology.owl#EMMO_9380ab64_0363_4804_b13f_3a8a94119a76
› http://emmo.info/base/emmo-mereotopology.owl#EMMO_517dfaf9_4970_41ac_81ee_d031627d2c7c
› http://emmo.info/base/emmo-mereotopology.owl#EMMO_6b7276a4_4b9d_440a_b577_0277539c0fc4
› http://emmo.info/base/emmo-mereotopology.owl#EMMO_ec2472ae_cf4a_46a5_8555_1556f5a6c3c5
› http://emmo.info/base/emmo-mereotopology.owl#EMMO_17e27c22_37e1_468c_9dd7_95e137f73e7f
› http://emmo.info/base/emmo-mereotopology.owl#EMMO_9cb984ca_48ad_4864_b09e_50d3fff19420

**Comment by emanueleghedini** [comment]
To be amended with the next EMMO release
