### ISSUE TITLE
emmo import 

### ISSUE THREAD

**Issue by JoanaFMorgado** [emmo-repo/EMMO#171]
Hello,

I was loading the SimDOME ontology and noticed that there is an issue with the import since there is (I can't find) no ontology with the URI as defined below see below. 
I think it should be replaced by ```owl:imports <http://emmo.info/emmo/1.0.0-beta>``` .

https://github.com/emmo-repo/EMMO/blob/252855eb73cad22dcfeb6f79c28878da73a86aa7/application/simdome.ttl#L12

Many thanks!

Kind Regards,
Joana

**Comment by jesper-friis** [comment]
Hi Joana. Sorry for being slow in looking at this. I hope this has been solved long ago. The file [EMMO/application/simdome.ttl](https://github.com/emmo-repo/EMMO/blob/252855eb73cad22dcfeb6f79c28878da73a86aa7/application/simdome.ttl#L12) is not part of master or the 1.0.0-beta2 develop branch. I guess it is moved to the SimDOME repository.

Ok to close this issue?

**Comment by JoanaFMorgado** [comment]
Hi Jesper,
No problem. yes, it is OK to close the issue.
Many thanks!
