### ISSUE TITLE
Use EMMO Units in Abox

### ISSUE THREAD

**Issue by paulzierep** [emmo-repo/EMMO#175]
The units in Emmo are defined as classes. How can this be used to instantiate flexible Abox data. For example, there can be a large amount of mixed units (m/kg^2). How could one proceed to add these units to a specific data value.

**Comment by kysrpex** [comment]
I noticed another point to take care of regarding the use of EMMO units in the ABox.

I am currently using the units by creating unit individuals and assigning the unit class as their type. The initial idea was to instantiate just one individual and use it as reference unit for all measurements.

However, the `hasReferenceUnit` relationship is inverse functional (alpha2). This means that I must use a different unit individual for each measurement. Is this the intended design?

If the above is not the intended deisgn, would it make sense to include individuals for the units already in the ontology file, just like a universe is included?

**Comment by jesper-friis** [comment]
@kysrpex, thanks for pointing out the issue. We have now changed `BasedQuantity hasReferenceUnit only BaseUnit` to `BasedQuantity hasReferenceUnit some BaseUnit`.

**Comment by jesper-friis** [comment]
@paulzierep. Quantities in EMMO have two direct spatial parts, a numerical (number, array, ...) and a reference unit. An individual quantity like "1.0 metre" would have quantity value the number individual 1.0 and reference unit a Metre individual. 

The reason that quantities and units are classes in EMMO is because of its physicalistic/nominalistic nature. This allows to express that the 1 metre I am measuring does not necessarily the same 1 metre you are measuring, since they are the result of two different measurement processes.

**Comment by paulzierep** [comment]
@jesper-friis Thank you for your reply. In this case, I assume that if I want to add a quantity individual of a unit that is not yet part of EMMO to the ABox, I need to introduce the corresponding unit class in the TBox? 

I have another question concerning this issue. We would like to annotate data using EMMO. For time series data we would not like to store the data as RDF but rather reference the data using standard mappings like: csvw and CSV-LD patterns. In this case, we would use a class that has a unit and a relation to another class that stores the location of the time series data. However, if we use the hasReferenceUnit of EMMO. The Fact++ reasoner infers, that the individual is a Quantity. A Quantity needs a hasQuantityValue (correct?). But in our case, we rather have an entire array that has a unit. How could this be implemented using EMMO ?

**Comment by jesper-friis** [comment]
> In this case, I assume that if I want to add a quantity individual of a unit that is not yet part of EMMO to the ABox, I need to introduce the corresponding unit class in the TBox?

Correct

A Quantity has a Numerical part, which can be a single scalar or a large array. My suggestion is to create a Numerical individual that stands for your time series. Using e.g. dcat you, can associate this individual to your data source.

**Comment by jesper-friis** [comment]
OK to close this issue?
