### ISSUE TITLE
Broken link 

### ISSUE THREAD

**Issue by gerhardgoldbeck** [emmo-repo/EMMO#179]
On https://github.com/emmo-repo/EMMO the link http://emmo.info/emmo does not work. It resolves to https://raw.githubusercontent.com/emmo-repo/EMMO/master/emmo.owl 
Should be 
https://raw.githubusercontent.com/emmo-repo/EMMO/master/emmo.ttl

**Comment by jesper-friis** [comment]
I can't find this broken link. Is it already resolved?

**Comment by gerhardgoldbeck** [comment]
All works.
