### ISSUE TITLE
Inverse relationships not explicitly declared

### ISSUE THREAD

**Issue by jesper-friis** [emmo-repo/EMMO#18]
From running OntOlogy Pitfall skanner! (OOPS!) on http://oops.linkeddata.es/

Results for P13: Inverse relationships not explicitly declared.17 cases | Minor

This pitfall appears when any relationship (except for those that are defined as symmetric properties using owl:SymmetricProperty) does not have an inverse relationship (owl:inverseOf) defined within the ontology.

• OOPS! has the following suggestions for the relationships without inverse:
› http://emmo.info/perspectives/emmo-existent.owl#EMMO_b2282816_b7a3_44c6_b2cb_3feff1ceb7fe could be inverse of http://emmo.info/perspectives/emmo-existent.owl#EMMO_a50d920d_1ee3_4668_9a73_5d80a1c6fe15
› http://emmo.info/base/emmo-mereotopology.owl#EMMO_7afbed84_7593_4a23_bd88_9d9c6b04e8f6 could be inverse of http://emmo.info/base/emmo-4d.owl#EMMO_f68030be_94b8_4c61_a161_886468558054
› http://emmo.info/base/emmo-4d.owl#EMMO_f68030be_94b8_4c61_a161_886468558054 could be inverse of http://emmo.info/base/emmo-4d.owl#EMMO_6e046dd0_9634_4013_b2b1_9cc468087c83

• Sorry, OOPS! has no suggestions for the following relationships without inverse:
› http://emmo.info/perspectives/emmo-existent.owl#EMMO_65a2c5b8_e4d8_4a51_b2f8_e55effc0547d
› http://emmo.info/perspectives/emmo-semiotics.owl#EMMO_eb3518bf_f799_4f9e_8c3e_ce59af11453b
› http://emmo.info/perspectives/emmo-semiotics.owl#EMMO_60577dea_9019_4537_ac41_80b0fb563d41
› http://emmo.info/perspectives/emmo-semiotics.owl#EMMO_39c3815d_8cae_4c8f_b2ff_eeba24bec455
› http://emmo.info/perspectives/emmo-semiotics.owl#EMMO_297999d6_c9e4_4262_9536_bd524d1c6e21
› http://emmo.info/perspectives/emmo-semiotics.owl#EMMO_2337e25c_3c60_43fc_a8f9_b11a3f974291
› http://emmo.info/base/emmo-mereotopology.owl#EMMO_03212fd7_abfd_4828_9c8e_62c293052d4b
› http://emmo.info/base/emmo-mereotopology.owl#EMMO_9380ab64_0363_4804_b13f_3a8a94119a76
› http://emmo.info/base/emmo-mereotopology.owl#EMMO_8c898653_1118_4682_9bbf_6cc334d16a99
› http://emmo.info/base/emmo-mereotopology.owl#EMMO_6b7276a4_4b9d_440a_b577_0277539c0fc4
› http://emmo.info/base/emmo-mereotopology.owl#EMMO_ec2472ae_cf4a_46a5_8555_1556f5a6c3c5

**Comment by nanodome** [comment]
It is not clear to me why failing to declare an inverse property would be a pitfall, when OWL provides the statement ObjectInverseOf() to declare the inverse of any relations, reducing by a factor 2 the number of properties to be declared and facilitating maintenance.

Moreover the suggestions provided by OOPS! are all wrong....
