### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by gerhardgoldbeck** [emmo-repo/EMMO#183]
The link on  "Use of EMMO in domain ontologies" https://github.com/emmo-repo/EMMO/blob/master/use-of-emmo-in-domain-ontologies in EMMO Readme is broken. Should probably link to https://github.com/emmo-repo/EMMO/blob/master/doc/EMMO_governance.md#domain-ontologies

**Comment by jesper-friis** [comment]
Fixed in commit 9ef30fc
