### ISSUE TITLE
Solve the microstructure URL in Readme

### ISSUE THREAD

**Issue by JoanaFMorgado** [emmo-repo/EMMO#187]
Hello 

I would like to kindly report a  small inconsistency in the EMMO [readme file](https://github.com/emmo-repo/EMMO#use-of-emmo-in-domain-ontologies)  in the microstructure ontology URL  - https://github.com/emmo-repo/domain-microstructure instead of https://github.com/emmo-repo/domain-ontology.

Many thanks and kind regards,
Joana

**Comment by jesper-friis** [comment]
Thanks Joana for pointing this out. A correction is now pushed to 1.0.0-beta3.
