### ISSUE TITLE
Recursive definitions

### ISSUE THREAD

**Issue by jesper-friis** [emmo-repo/EMMO#19]
From running OntOlogy Pitfall skanner! (OOPS!) on http://oops.linkeddata.es/

Results for P24: Using recursive definitions.5 cases | Important

An ontology element (a class, an object property or a datatype property) is used in its own definition. Some examples of this would be: (a) the definition of a class as the enumeration of several classes including itself; (b) the appearance of a class within its owl:equivalentClass or rdfs:subClassOf axioms; (c) the appearance of an object property in its rdfs:domain or range rdfs:range definitions; or (d) the appearance of a datatype property in its rdfs:domain definition.

• This pitfall appears in the following elements:
› http://emmo.info/base/emmo-physical.owl#EMMO_0f795e3e_c602_4577_9a43_d5a231aa1360
› http://emmo.info/base/emmo-physical.owl#EMMO_29072ec4_ffcb_42fb_bdc7_26f05a2e9873
› http://emmo.info/base/emmo-physical.owl#EMMO_c5ddfdba_c074_4aa4_ad6b_1ac4942d300d
› http://emmo.info/domains/emmo-material.owl#EMMO_70dac51e_bddd_48c2_8a98_7d8395e91fc2
› http://emmo.info/domains/emmo-material.owl#EMMO_5b2222df_4da6_442f_8244_96e9e45887d1

The corresponding labels are:
  - elementary
  - void
  - physical
  - field
  - matter

**Comment by emanueleghedini** [comment]
If a class is declared as primitive, why this should be a pitfall?!?!

**Comment by jesper-friis** [comment]
Agree. That recursive definitions are allowed in OWL seems also to be confirmed by the OWL Primer: https://www.w3.org/TR/owl2-primer/#Property_Restrictions 

Last paragraph of Sec. 5.2:
As a special case of individuals being interlinked by properties, an individual might be linked to itself. The following example shows how to represent the idea that all narcissists love themselves. 

 EquivalentClasses(
   :NarcisticPerson 
   ObjectHasSelf( :loves ) 
 )
