### ISSUE TITLE
Wrong ID/subclassing for Graphics in "EMMO:Chemistry" (beta4, refactoring branches)

### ISSUE THREAD

**Issue by adhamhashibon** [emmo-repo/EMMO#195]
issue: when loading the Chemistry reference ontology, then class `ChemicalComposition` is under `Representation` which is under id: `EMMO_c7.....a55f3`. 

version: at least the branches `1.0.0.0-beta4 `and `refactoring` are concerned 

this ID seems to belong to class `Graphical` (see branch `origin/chemistry`). 

moreover, the class "Representation" seems to be only in the reference ontology Chemistry.ttl. 

It seems something that should be under EMMO:Symbolic. @emanueleghedini @jesper-friis @gerhardgoldbeck what do you recon?

**Comment by jesper-friis** [comment]
Nice spotted. `Representation` should be in perceptual. I will move it and create a PR.

**Comment by adhamhashibon** [comment]
@jesper-friis is this now resolved (i.e., part of a pull request and is fixed etc), if so can we close it?

**Comment by jesper-friis** [comment]
Yes, this is resolved
