### ISSUE TITLE
Number does not subclass from hasNumericalData

### ISSUE THREAD

**Issue by adhamhashibon** [emmo-repo/EMMO#203]
While all subclasses of Number(disciplines/math.ttl::EMMO_21f56795_ee72_4858_b571_11cfaa59c1a8 rdf:type owl:Class ;) have the property hasNumericalData, it itself does not have it. 

is there a reason for this ? in general it would be nicer if the subclasses inherit common properties, as it is better practice. 

@jesper-friis @emanueleghedini can we add hasNumericalData as a property of Number, and then overload it as needed for the subclasses? what do you think.

**Comment by jesper-friis** [comment]
FaCT++ does not support user-defined datatypes and there is no standard datatype for a number that includes booleans, integers and floats.

**Comment by jesper-friis** [comment]
A class (Number) should never subclass a data property (hasNumericalData).
