### ISSUE TITLE
Elaboration needs elaboration ;-) 

### ISSUE THREAD

**Issue by adhamhashibon** [emmo-repo/EMMO#204]
The term EMMO:Elaboration refers in EMMO to the actual work, while the dictionary meaning of elaboration is the specification of the steps, or there further specification. Since specification is not actual work meant in EMMO, a new term is needed. One thing proposed by Michael Noeske (what's your GitHub handle???) is *Opus* (Latin: Piece of Work) which has nice connotation too. Why not? any other suggestions like "PieceOfWork", "UnitOfWork", or simple "Work" or "Labour", or "Tasks"...

**Comment by adhamhashibon** [comment]
note, that once we change this, we need to also change the description/annotation of sub classes too. 

what about WorkPart?

**Comment by jesper-friis** [comment]
Elaboration is an alternative label for procedure. I think that the elucidation of procedure is quite clear; "the process in which an agent works with some entities according to some operative rules".

Work is another alternative label for Procedure.
Task is a procedure that is a part of a workflow.
