### ISSUE TITLE
beta4: Why do have hasMeasuredUncertainty and hasQuantity different perspectives?

### ISSUE THREAD

**Issue by MBueschelberger** [emmo-repo/EMMO#207]
Dear EMMOers,

Concerning beta4, I was wondering why `hasMeasuredUncertainty` is considered to a semiotical relationship and why `hasQuantity` is a holistic relationship. 

Is it because a measurement is considered to be a stongly semiotic process and assigning a quantity to another entity not?

Would be really looking forward to your answer!

**Comment by jesper-friis** [comment]
Things might have changed since you created this issue. There should be difference. `hasMeasuredUncertainty` is a subproperty of `hasQuantity`. Both relations are defined in metrology, which depends on both holistic and semiotics.
