### ISSUE TITLE
Adding rdfs:label with similar literal as skos:prefLabel

### ISSUE THREAD

**Issue by paulzierep** [emmo-repo/EMMO#209]
Most tools use as a minimul rdfs:label for rendering not skos:prefLabel. Since EMMO class names are not human-readable, it is crucial to allow for label based rendering. E.g.: OntoPanel (https://github.com/yuechenbam/yuechenbam.github.io) which is used by multiple projects can only render based on rdfs:label.

Therefore, I would propose to add rdfs:label with the same literal as skos:prefLabel to all concepts.

If this is accepted, I can also write a script to automatically do it.

**Comment by jesper-friis** [comment]
skos:prefLabel is a subproperty of rdfs:label (an relation that is explicitly included in EMMO) exactly to support such tools.

**Comment by jesper-friis** [comment]
Closing, since I don't think this is an issue. 

If OntoPanel is not able to infer that skos:prefLabel is a rdfs:label, you could either file a bug report for OntoPanel or create a local ontology that imports EMMO and dublicate all skos:prefLabel as rdfs:label.
