### ISSUE TITLE
URI contains file extension

### ISSUE THREAD

**Issue by jesper-friis** [emmo-repo/EMMO#22]
From running OntOlogy Pitfall skanner! (OOPS!) on http://oops.linkeddata.es/

Results for P36: URI contains file extension.ontology* | Minor

This pitfall occurs if file extensions such as ".owl", ".rdf", ".ttl", ".n3" and ".rdfxml" are included in an ontology URI. This pitfall is related with the recommendations provided in [9].

*This pitfall applies to the ontology in general instead of specific elements.

 [9] Archer, P., Goedertier, S., and Loutas, N. (2012). D7. 1.3-study on persistent URIs, with identification of best practices and recommendations on the topic for the Mss and the EC. PwC EU Services.

**Comment by emanueleghedini** [comment]
Agree on file extensions.

However, the same source suggests to avoid versioning... which is against the common usage of OWL ontologies.

**Comment by emanueleghedini** [comment]
Removed all extension in 1.0.0-alpha
