### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by jesper-friis** [emmo-repo/EMMO#23]
From running OntOlogy Pitfall skanner! (OOPS!) on http://oops.linkeddata.es/

Results for P41: No license declared.ontology* | Important Important

The ontology metadata omits information about the license that applies to the ontology.

*This pitfall applies to the ontology in general instead of specific elements.

**Comment by emanueleghedini** [comment]
We have license declaration for all EMMO modules. Maybe we should declare it using a more general annotation properties such as dc:license, for OOPS! to recognize it.

**Comment by jesper-friis** [comment]
Fixed in PR #90

**Comment by Talla977** [comment]
Hello everyone.
I am faced with this pitfall 41 problem. I declared a license as follows:
dcterms:license
 https://creativecommons.org/licenses/by/4.0/

But my mistake is still crooked. Does anyone have any idea why it’s not working?
