### ISSUE TITLE
CelsiusTemperature

### ISSUE THREAD

**Issue by hothello** [emmo-repo/EMMO#233]
Wrong link in the **qdtReference**. The correct link is:
"http://qudt.org/vocab/quantitykind/CelsiusTemperature"

**Comment by jesper-friis** [comment]
Which branch are you looking at? It is correct in "amended-metrology" which we soon will merge back into branch 1.0.0-beta4.

**Comment by hothello** [comment]
I am in the 1.0.0-beta4. Then forget about this :)
