### ISSUE TITLE
rdf:comments

### ISSUE THREAD

**Issue by hothello** [emmo-repo/EMMO#235]
I am reading the description of the top classes of EMMO. I will use this topic as a memo for comments that I found not clear, or whose description does no longer agree with the taxonomy of 1.0.0-beta4

**Comment by hothello** [comment]
In Peristence: the description opens with:
> The interest is on the 4D object as it extends in time (process) or as it persists in time (object):
I think this should read:
> The interest is on a 4D object as it extends in space (object) or persists in time (process).

**Comment by jesper-friis** [comment]
Hi Otello, I don't think that there is anything wrong with the initial formulation. The main difference between object and process is how you treat time.

**Comment by hothello** [comment]
why then saying that an object focuses on spatial configuration?

**Comment by jesper-friis** [comment]
Because that is also true. I have had the same thoughts about the formulation as you, but ended up realising that the original formulation is very good. The first sentence focus on the two different ways to consider time. The bullet points brings in the aspect of space vs time.

**Comment by hothello** [comment]
Sure!
