### ISSUE TITLE
Ontology IRI for v1.0.0-beta5 pre-inferred

### ISSUE THREAD

**Issue by jsimonclark** [emmo-repo/EMMO#236]
The Ontology IRI for v1.0.0-beta5 pre-inferred is set to Jesper's local default (http://www.semanticweb.org/jesperf/ontologies/2023/6/untitled-ontology-54). Should be updated to the proper IRI.

https://emmo-repo.github.io/versions/1.0.0-beta5/emmo-inferred.ttl

**Comment by jesper-friis** [comment]
This should be fixed by now.
