### ISSUE TITLE
Symmetric or transitive object properties?

### ISSUE THREAD

**Issue by jesper-friis** [emmo-repo/EMMO#24]
From running OntOlogy Pitfall skanner! (OOPS!) on http://oops.linkeddata.es/

SUGGESTION: symmetric or transitive object properties.3 cases

The domain and range axioms are equal for each of the following object properties. Could they be symmetric or transitive?
› http://emmo.info/perspectives/emmo-existent.owl#EMMO_b2282816_b7a3_44c6_b2cb_3feff1ceb7fe (has spatial direct part)
› http://emmo.info/perspectives/emmo-existent.owl#EMMO_a50d920d_1ee3_4668_9a73_5d80a1c6fe15 (has spatiotemporal direct part)
› http://emmo.info/base/emmo-mereotopology.owl#EMMO_ec2472ae_cf4a_46a5_8555_1556f5a6c3c5 (emmo relation)

**Comment by jesper-friis** [comment]
I think this should be a non-fix. 

`has_spatial_direct_part` and `has_spatiotemporal_direct_part` should be neither symmetric nor transitive. I think the same is the case for `emmo_relation`.

**Comment by emanueleghedini** [comment]
Agree for the _emmo_relation_ case.
