### ISSUE TITLE
Check URI pattern

### ISSUE THREAD

**Issue by pierluigidelnostro** [emmo-repo/EMMO#258]
Hello, 

I found 2 classes that seem to have a URI pattern which is not compliant with the notation EMMO_ _HEXCODE_ :

- in isq.ttl <http://emmo.info/emmo#2ce04004_62cf_4394_b6a2_b45fce1aebfe>
- in models.ttl <http://emmo.info/emmo#1c7f2dfe_0db4_4bf6_a0f6_853054a34ead>

**Comment by pierluigidelnostro** [comment]
actually there are many others where the hexadecimal has not the EMMO_ prefix

**Comment by hothello** [comment]
I have added a script to check and replace the non-standard IRIs. In this [pull request](https://github.com/emmo-repo/EMMO/pull/262) to the beta5, all of them have been changed to the standard `EMMO_hex_hex_hex_hex_hex` format.

**Comment by jesper-friis** [comment]
Closing this issue since it was fixed in PR #262
