### ISSUE TITLE
Add datatypes to EMMO

### ISSUE THREAD

**Issue by jesper-friis** [emmo-repo/EMMO#27]
This is a first draft for adding datatypes to EMMO. Datatypes (here called Value) are essential for using EMMO in actual applications. 

Would it be better to rename "Value" to  "Datatype"? I have been using Value here, since it feels more natural to say that a property has part Value than DataType.

The SumType is an interesting suggestion by Petter that needs to be discussed to get right. It will allow an EMMO-based application ontology to specify that e.g. salt concentration may be represented with either a single average value, a statistical distribution or spatially resolved grid.

**Edit**: Updated `CompoundItem`.

Classes
-------
Value
  - subclassOf SymbolicDomain     (??)
  Subclasses:
    * BasicValue
        - disjointUnionOf Boolean, Number, String
    * NumericValue
        - disjointUnionOf Number, NumericArray
    * Array
        - hasDimension some Dimension
        Subclasses:
          * NumericArray
              - hasSpatialPart some Number
              Subclasses:
              * Matrix
                  - hasDimension exactly 2 Dimension
    * CompoundValue
        An unordered set of key-value pairs, like C struct's or Python dict's.
        - hasSpatialPart some CompoundItem
    * SumType
        How to implement this?
        - hasSpatialPart X or Y or Z    (??)

Number
  * Natural
  * Integer
  * Rational
      Subclasses:
        * Float
  * Real
  * Complex
  * Quaternion
  * Octonion           (for Georg :-)

Boolean
  - subclassOf Mathematical

CompoundItem
  A CompoundItem has two spatial parts, 'item' and 'value'.  It makes a
  connection between an already defined concept (an EMMO Item) and a corresponding value.
  - subclassOf SymbolicStructured    ??
  - hasKey some Item         (should we use "exact 1" Item ??)
  - hasValue some Value         (should we use "exact 1" Value ??)

Dimension
  Dimensions are used to construct arrays. They have a size and may be chained using hasNextDimension to provide an ordered list of dimensions. It would also be very useful to assign a name to each dimension or a quantity. Should we use value restrictions for that?
  - subclassOf Mathematical
  - hasValue some Natural               (or exactly 1?)
  - hasNextDimension some Dimension     (or max 1?)

Relations
---------
hasValue
  - subclass of: hasSpatialPart
  - domain: Item                        # should it be more restricted?
  - range: Value

hasKey
  - subrelationOf hasSpatialPart
  - domain: CompoundItem
  - range: Item

hasDimension
  Cardinality may be used to specify exact, max or min size of a dimension.
  Otherwise the dimension size must be assigned at instantiation.
  - subclass of: hasSpatialPart
  - domain: Array or Property?
  - range: Dimension

hasNextDimension
  - subclass of: hasSpatialPart
  - domain: Dimension
  - range: Dimension

**Comment by jesper-friis** [comment]
The branch issue27-emmo-datatypes implements the above suggestion

**Comment by jesper-friis** [comment]
There is an issue with the Dimension as it is described above. Lets say we are creating a domain ontology and want to add the StiffnessTensor as a subclass of Pressure under derived physical quantities. It is a symmetric tensor of rank 4, where each of the 4 dimensions is of size 3. EMMO should provide the means to specify this, but how?

Should we create Dimension individuals for each of the 4 dimensions, each with a size, a name and a next dimension (except for the last one)? 

How should we specify that the StiffnessTensor is a symmetric tensor? With a value restriction?

**Comment by mospring** [comment]
Why not separate rank from it? First an array has a rank, e.g. 4. Then for each of these 4  "orders"/"degrees" we give the dimension? 

Individuals make it harder to assign variable dimension names to it a dimension I guess.

**Comment by ahashibon** [comment]
thanks @jesper-friis 
I am not sure that we need low level data types, this should be implementation specific, my main concern, if I understand correctly is, e.g., with the following :

> CompoundItem
> A CompoundItem has two spatial parts, 'name' and 'value'. It makes a
> connection between the name and the value.
> 
> subclassOf Composition (??)
> hasName some String (should we use "exact 1" String ??)
> hasValue some Value (should we use "exact 1" Value ??)
> 

first: do you mean that we can define a data point like "key" -> value  maps with arbitrary "key" set by user on individual level. 

If yes, I would strongly recommend to rethink this, as it is introducing a syntactic layer that will enable polluting the ontology with syntactic garbage, as the key is random, unless we limit its use in some way.  A better solution is to define specific entities rather than keys. See e.g., https://gitlab.cc-asp.fraunhofer.de/mat-info/ontology/materials-composition which we wold like to port to EMMO after review. 

I will make an issue for this here too.

**Comment by jesper-friis** [comment]
@ahashibon, you have a very good point. The idea behind CompoundValue was to allow the user to be able to describe more complex data. But you are right, arbitrary keys it allows to bypass the semantics. We should remove the CompoundValue.

**Comment by ahashibon** [comment]
maybe constraining the keys to EMMO classes of specific types like in SimPhoNY CUDS would be good.
It will allow to bring the CUDS itself into EMMO naturally.

**Comment by jesper-friis** [comment]
They already are via the restriction `hasKey some Item`.
