### ISSUE TITLE
Add chemical identifiers

### ISSUE THREAD

**Issue by eibar-flores** [emmo-repo/EMMO#274]
Is it possible to add additional chemical identifiers? Some widely used are not yet supported by emmo. 

- SMILES (isA ChemicalNomenclature): http://opensmiles.org/opensmiles.html

- InChI Key (isA IUPACNomenclature): a hashed version of the full InChI (using the SHA-256 algorithm, designed to allow for easy web searches of chemical compounds.

**Comment by jesper-friis** [comment]
Would it make sense to add two new annotation properties for them in the chemistry module?

**Comment by eibar-flores** [comment]
> Would it make sense to add two new annotation properties for them in the chemistry module?

It is a possibility, yes. However, given InChI is already defined in EMMO, wouldn't it be confusing to define InChI Key and SMILES in a different module?

**Comment by jesper-friis** [comment]
I was thinking about the chemistry module in EMMO, the same module in which InChI is defined.

**Comment by jesper-friis** [comment]
Where you thinking about something like this: #275

**Comment by eibar-flores** [comment]
> Where you thinking about something like this: #275

Excellent, this works. Thanks for addressing it so quickly!

**Comment by jesper-friis** [comment]
We will review the PR in the EMMO dev. meeting on Thursday. Then it might be merged.
