### ISSUE TITLE
Derived SI units should always contain refence to SI base units 

### ISSUE THREAD

**Issue by markdoerr** [emmo-repo/EMMO#280]
It is very hard to create a SPARQL query to EMMO that directly retrieves the SIBaseUnit of derived SIDimensionalUnits.

E.g., force / Newton 
1 N =  1 kg m / s²

etc.

I propose to add a property:

hasSIBaseSymbolValue

In the case of force it would also be nice to be able to directly query, from which SIBaseUnits it was derived.
(without parsing the hasDimensionString )

**Comment by jesper-friis** [comment]
Thanks for your input. I see that such a property with the base units would be useful, but it will also increase the maintenance burden. Maybe we could add a script for adding and maintaining it automatically. 

Not sure whether it should be an annotation or data property, though.

**Comment by markdoerr** [comment]
Hej, @jesper-friis ,
I think, a script is a good idea.
(I was also wavering between annotation and data property, a data property might be more reliable for reasoning and SPARQL queries) 

Potential queries:
A pressure measurement resulted in 5 MPa, please convert the value, using only SIBaseUnits (for standardised storage in a data repository).

**Comment by jesper-friis** [comment]
Closing this issue

@markdoerr, as a final comment we have introduced a new datatype SIQuantityDatatype and a corresponding data property hasDimensionString. However, these were for the convenience of assigning values to physical properties, not to simplify sparql queries.
