### ISSUE TITLE
Missleading Class-Subclass hierachy in SIDimensionalUnits

### ISSUE THREAD

**Issue by markdoerr** [emmo-repo/EMMO#281]
MassUnit, TemperatureUnit, LengthUnit, etc. are currently modelled as subclasses of SIDemsinalUnit.

This is not correct, as there exist non-SI MassUnits, LengthUnits, TemperatureUnits ....

Shouldn't the subclasses be better called "MassSIUnit", "TemperatureSIUnit", "LengthSIUnit" ?

**Comment by jesper-friis** [comment]
Agree, there exist non-SI MassUnits, LengthUnits, TemperatureUnits ....

However, the "SI" in the label of SIDimensionalUnit does not mean that it is the class of dimensional SI units (which we would have called DimensionalSIUnit). Instead it refer to dimensional units who's physical dimensionality is described according to SI.

**Comment by markdoerr** [comment]
Thanks, @jesper-friis , for the fast  explanation.
Since this subtle difference, you described above, might not clear / obvious to many scientists, it should be worth an design explanation in the annotation of the **SIDimensionalUnit** class, e.g. like:
`All derived subclasses of SIDemensionalIUnit are based on physical dimensionalities as described in the [SI specification](https://www.bipm.org/documents/20126/41483022/SI-Brochure-9-EN.pdf) `

**Comment by jesper-friis** [comment]
done
