### ISSUE TITLE
http://emmo.info/emmo/middle/isq redirects to a non-existing file (404 error)

### ISSUE THREAD

**Issue by k00ni** [emmo-repo/EMMO#285]
Ontology IRI `http://emmo.info/emmo/middle/isq` redirects to `https://raw.githubusercontent.com/emmo-repo/EMMO/middle/isq/emmo.ttl`, which does not exist. It is used here for instance: https://github.com/emmo-repo/EMMO/blob/master/middle/isq.ttl#L9

This can be solved by either:
* fix the redirect to go to the correct file or
* adapt the ontology related content

**Comment by jesper-friis** [comment]
Thanks @k00ni for the comment. The current IRI https://w3id.org/emmo/disciplines/isq now resolves.
