### ISSUE TITLE
Value other than number for physics quanity

### ISSUE THREAD

**Issue by ahashibon** [emmo-repo/EMMO#29]
currently a physics quantity has a number and unit, however, this may mean (if we ugnore transitivness) that emmo only supports scalar quanititeis like mass or Temperature, not e.g., force or velocity etc which are vector quantities or tensor quanitities that descrive how a physics quantitiy is represented int time-space. 

# Proposal: 
1. replace number by value in physical quantity
   has_spatial_part some ~~number~~ value 
   then either: 
   - add value as a mathematical, since a value maybe a function or any other mathematical, not only a number (and can also be a number of course) and let value be a super class of any scalar, vector or any other emmo:mathemtatical type 
  OR alternatively, 
  - the physics quantities themselves subclass from vector_quantity, tensor_quantity, etc. and each would have a value that is a mathematical 

**NOTE** this is not about the data type which should not be part of EMMO it self, but the implementations, this is about the representation of physics quantities that are not simple numbers (the data type may refer for example to double or float, in emmo it is simply a read number). 

# maybe related to #27

**Comment by ahashibon** [comment]
@jesper-friis would you please comment if it is overlapping with #27 in your opinion? I think #27 is complementary but not same, however, open to other interpretations. Thanks.

**Comment by jesper-friis** [comment]
One important motivation for issue #27 is to be able to semantically describe dimensionality. 

I guess that we can be even more specific. A suggestion is to say that Property hasSpatialPart  some Value and QuantitativeProperty hasSpatialPart some NumericValue.

**Comment by jesper-friis** [comment]
If we also want to be able to semantically express that a PhysicalQuantity, like velocity, may e.g. be represented as either a scalar (absolute value) **or** a vector **or** a velocity distribution, then we need the SumType suggested by Petter.

I think that SumTypes would be very useful to have, but I am not sure how to formulate it in EMMO.

**Comment by emanueleghedini** [comment]
Done in 1.0.0-alpha. 

Quantities now are made of a numerical object (scalar, vector, matrix) and a reference unit.
