### ISSUE TITLE
wong link to domain-microstructure on https://github.com/emmo-repo/EMMO

### ISSUE THREAD

**Issue by HoWilgh** [emmo-repo/EMMO#293]
On "https://github.com/emmo-repo/EMMO"  the link next to "Microstructure domain ontology" which is "https://github.com/emmo-repo/domain-ontology" is wrong and should be
https://github.com/emmo-repo/domain-microstructure

**Comment by jesper-friis** [comment]
Thanks @HoWilgh . Fixed in 1.0.0.
