### ISSUE TITLE
Correct description of SMILES annotation property

### ISSUE THREAD

**Issue by eibar-flores** [emmo-repo/EMMO#295]
The SMILES representation has been added as annotation property in the Chemistry Discipline of EMMO: https://w3id.org/emmo/disciplines/chemistry#EMMO_2e0b0f1b_ba90_4827_af5a_92b826cb90de.

However, the prefLabel and elucidation need to be corrected:

|             | Currently                                          | Suggested Correction                     | Reason                                                                                        |
|-------------|----------------------------------------------------|-------------------------------|-----------------------------------------------------------------------------------------------|
| prefLabel   | smileReference                                     | SMILESReference               | The last S in SMILES is part of the acronym.                                                  |
| Elucidation | OpenSMILE representation of a molecular structure. | OpenSMILES representation ... | Same as above. |

I would also suggest adding a wikipediaReference  [to this page](https://en.wikipedia.org/wiki/Simplified_molecular-input_line-entry_system), and if possible link the class to the [open SMILES specification](http://opensmiles.org/opensmiles.html), e.g. via a dcterms:source property.

**Comment by emanueleghedini** [comment]
Done. Thanks.
