### ISSUE TITLE
Chemical composition and other "compound physical quantities" 

### ISSUE THREAD

**Issue by ahashibon** [emmo-repo/EMMO#30]
in many cases in physics and materials science we need to relate a quantity to multiple "keys". Having a data structure supported for this in the ontology like in #27 may lead to overuse and to "injection" of EAV data paradigms with lower semantic power than is presented in EMMO. 
here another solution is proposed that alleviates the need for arbitrary keys in data structures. As an example we consider the chemical composition: "$Al 40 %, O 60 %" of some crystal. 

here obviously one needs to specify an element, and a corresponding physical quantity (the mass %). instead of defining a map with arbitrary strings, like "Al" --> value "40 %"  we can and "O" --> "60 %", we can define that 

chemical composition is a physical quantity that has in addition to number and unit an IUPAC chemical element (or molecule). 

then the chemical composition of an alloy can simply have properties of all chemical composition instances, without the need for explicit keys.

**Comment by ahashibon** [comment]
Another option is of course to add a chemical content that has both an element and a quanitity (the mass fraction for example) and having_. 

* chemical composition has part some chemical content
* chemical content has part element 
* chemical content has part value.

**Comment by jesper-friis** [comment]
Yes, the latter is the right way to go. I would rewrite it as:

    ChemicalComposition hasSpatialPart some ChemicalContent

    ChemicalContent isA PhysicalQuantity
    ChemicalContent hasSpatialPart exactly 1 ChemicalComponent
    ChemicalContent hasSpatialPart exactly 1 Real                 (inherited from PhysicalQuantity)

The subclasses of `ChemicalComponent` should be all possible chemical components, both pure elements as well as other components like CO2, SiO2, ... When possible, they should refer to an external standard, like the IUPAC Gold Book.

**Comment by jesper-friis** [comment]
A draft implementation is pushed to https://github.com/jesper-friis/emmo-units and https://gitlab.cc-asp.fraunhofer.de/mat-info/ontology/emmo-units for review.

**Comment by ahashibon** [comment]
@jesper-friis is it necessary to have chemcial composition part of the emmo-unit or can it be part of a emmo-chemical-composition or a chemical ontology branch.

**Comment by jesper-friis** [comment]
Currently ChemicalComposition is defined in emmo-si-units, but it is definitely possible to factor it out. It would make sense, since it is (as far as I know) not defined in the SI system.

**Comment by jesper-friis** [comment]
This is outside the scope of mid-level EMMO, but very interesting to follow up in domain ontologies.
