### ISSUE TITLE
1.0.0-rc1: Terms / Classes "ContinuumManufacturing" and "DiscreteManufacturing" are not well described / defined, please improve.

### ISSUE THREAD

**Issue by markdoerr** [emmo-repo/EMMO#308]
The classes **ContinuumManufacturing** and **DiscreteManufacturing**  are not well separated:

**ContinuumManufacturing** is described as "A manufacturing process whose product is the result of the combination of more substances." 
With the example: 
"Synthesis of materials, the preparation of a cake."

**DiscreteManufacturing** is described as "A manufacturing process aimed to the production of a device made of specific components."
With the example:
"Assemblying a bicycle, building a car."

But what is the key difference ? In both processes, specific substances/components are combined.
In the case of a reaction or cake the components are reactants, flour, rosins, nuts, etc. in the case of a bicyle, the components are tubes, welding metal, screws, nuts and bolts. Is the welding process in the bicycle manufacturing continuous or discrete ? 
Is the process of making the screws of a bicycle discrete or continuous ? If this and the welding process are continuous, what if one wants do describe the complete bicycle manufacturing process, including the screws and welding (=ContinuumDiscretManufacuring) ?  A similar situation appears when describing making a rosin-cake ;)

Why is this separation of Manufacturing Processes important in EMMO ?

Personally, I would remove the whole "Manufacturing" branch in EMMO, since this could be much better modeled in a Domain specific ontology.

**Comment by emanueleghedini** [comment]
The manufacturing module in the 1.0.0-rc3 has been completely refactored, and refers mainly to DIN 8580:2020 and other relevant standards. The two mentioned classes were leftovers of an old initial commit and the concepts that they were intended to express are now better explained under WorkpieceManufacturing and MaterialsProcessing.
