### ISSUE TITLE
IUPACName is a Class and an Annotation Property

### ISSUE THREAD

**Issue by jsimonclark** [emmo-repo/EMMO#325]
IUPACName is the prefLabel for both a Class and an Annotation Property. This creates problems when creating linked data instances. Suggest to re-name the Annotation Property hasIUPACName (so as also to be consistent with property naming conventions lowerCamelCase).

**Comment by jesper-friis** [comment]
> IUPACName is the prefLabel for both a Class and an Annotation Property. This creates problems when creating linked data instances. Suggest to re-name the Annotation Property hasIUPACName (so as also to be consistent with property naming conventions lowerCamelCase).

Which version of EMMO do you see this in? In 1.0.0-rc3 we do not have an `IUPACName` annotation property as far as I can see.
