### ISSUE TITLE
domains catalogue file wrong path

### ISSUE THREAD

**Issue by ahashibon** [emmo-repo/EMMO#34]
the catalogue file under domains in the emmo-units branch (see #15 ) contains some wrong references: 
`<uri id="Automatically generated entry, Timestamp=1577294513690" name="http://emmo.info/domains/emmo-si-units.owl" uri="emmo-si-units.owl"/>
`
--> there is no emmo-si-units under domains. 

also need to replace local references as in: 

`<uri id="Imports Wizard Entry" name="http://emmo.info/emmo.owl" uri="file:/home/jesperf/prosjekter/EMMC/emmo/emmo.owl"/>
`

**Comment by jesper-friis** [comment]
Should be fixed, also in the 'emmo-units' branch. Pull request #37 also remove auto-update of the catalog files.
