### ISSUE TITLE
Hands-on Examples with instance data

### ISSUE THREAD

**Issue by GeorgFerdinandSchneider** [emmo-repo/EMMO#38]
Dear EMMO developers,

I have been recently looking into EMMO an it’s seems to be a great ontology in the materials domain.

It is very well documented (e.g. [training](https://emmc.info/events/emmc-csa-webinar-introductions-to-ontology-and-interoperability/#comment-219)), however, I am missing an examples section where hands-on examples are presented. Maybe I just did not find them?

From other well known ontologies, e.g. SOSA https://www.w3.org/TR/vocab-ssn/#examples, these kind of examples are provided, which are very helpful to figure out the usage.

For instance it would be interesting to represent the following data:

Material: [55NiCrMoV6 ](http://www.ccsteels.com/Tool_steel/675.html)

CHEMICAL COMPOSITION (WEIGHT %)
C (％):    0.50 ～ 0.60
Si(％):    0.10 ～ 0.40
Mn(％):   0.65 ～ 0.95
P(％)≤:   0.030
S(％)≤:   0.030
Cr(％):    0.60 ～ 0.80
Mo(％):   0.25 ～ 0.35
V(％):     0.07 ～ 0.12
Other(％):    Ni 1.50 ～ 1.80 
MECHANICAL PROPERTIES - HOT WORKING, HEAT TREATMENT AND HARDNESS
Hot working tenperature /℃: 1050～850
Annealing temperature /℃:   650-710
Hardness after annealing ≤HBW:  240
Quenching temperature /℃:  830 - 870

Best

Georg

**Comment by sebastienh** [comment]
I agree with the previous comment: congratulation on your work on EMMO! I take the occasion to add another example suggestion in order to facilitate the use. A simple example like "guitar" -> hasSpatialPart -> "cord" with the relationships necessary with the/a Manufacturing Process, the acoustical perception and a description of the cord materials down to elementary would be really useful I think. It would cover a big part of the ontology in a simple manner. 

Thank you,

Sébastien

**Comment by emanueleghedini** [comment]
Thanks for your intereset in the EMMO, and sorry for the delay in the feedback.

Regarding hands-on examples, we are working now to practical ontologization of modelling and manufacturing cases within the framework of H2020 projects. We will publish and disseminate the outcome of these activities, together with new graphical schema to represent user cases. It's a huge work that requires adjustments in the mid-level of the EMMO: we should be able to provide some examples in 2-3 months, and a full seminar about it in the framework of the SimDOME project.

Regarding data representation, we are currently investigating what falls in the field of the EMMO and what is not. The EMMO is able to describe the syntax of data format together with its semantic meaning; however it is not something that can be implemented easily in OWL when the syntax is complex (e.g. a CHEMKIN input file). We have now a syntactical representation of PhysicalQuantities according to the ISQ and SI, that covers a [value][unit] data format. 
More complex format (like in the 55NiCrMoV6 example) may be addressed as a whole and leave the implementation the burden of syntactically decompose the data format and populate the ontology with single [value][unit] properties.

Regarding the guitar example, I agree that we need easy to understand examples that spans through all the wide range of perspectives that the EMMO is providing; however, this can be done only now after we changed the EMMO structure and tested the mid-level with practical cases within our H2020 projects.

Summarizing, we plan to start extensive dissemination about practical EMMO usage in very next few months, in the framework of SimDOME and OntoTrans projects.
