### ISSUE TITLE
BaseUnit has too many specific units

### ISSUE THREAD

**Issue by ahashibon** [emmo-repo/EMMO#40]
I agree we need to standardise on SI units, however, we not make it more explicit and open and consistent as follows: 

1. The BaseUnit class, has subclasses: ElectricUnit, LengthUnit, etc. 
2. e.g., LengthUnit will have a subclass BaseLengthUnit which has Metre and other units
3. alternatively, LengthUnit has a subclass all possible units needed, and the Meter will also inherit from BaseSiUnit, which is another class we need to have. 

In this way we eliminate the clutter in the actual quantities having to add possible units in the class definition. For example: 

![image](https://user-images.githubusercontent.com/6462558/75232793-1c61ec80-57b8-11ea-8b35-d5dde0236910.png)

for Area, we simply put 

hasUnit Some AreaUnit, 

isn't this much more elegant? 

@emanueleghedini @jesper-friis your comments please? 

thanks.

**Comment by ahashibon** [comment]
same thing for 
![image](https://user-images.githubusercontent.com/6462558/75234013-1967fb80-57ba-11ea-8b6a-0c1a9b40bf38.png)

why have seconds and days etc... this should be changeable for each User Case, and hence propose here and in all quantities to just on the top EMMO levels mention the type of unit:

Time hasUnit TImeUnit 

and TimeUnit is the superclass of all relevant time units, like seconds, days, minutes, hours, MarchianHouers, etc...

**Comment by jesper-friis** [comment]
I agree that this is not very clean. I think we simply should remove all the hasUnit relations from the physical quantities and only associate units their corresponding physical quantity.

**Comment by jesper-friis** [comment]
This also solves the conceptual mistake that Emanuele pointed out. 

Agree?

**Comment by jesper-friis** [comment]
The physical dimensions introduced in 1.0.0-alpha solves this in a clean way.
