### ISSUE TITLE
human readable IRI

### ISSUE THREAD

**Issue by ahashibon** [emmo-repo/EMMO#47]
currently IRIs are complex, e.g., http://emmo.info/latest/domains/emmo-material.owl#EMMO_a2b006f2_bbfd_4dba_bcaa_3fca20cd6be1
for a machine it does not matter if its like that or something like http://emmo.info/latest/domains/emmo-material.owl#EMMO_UNIT_MASS

the latter is much simpler. Are there any advantages for UUID like IRI#s?

**Comment by jesper-friis** [comment]
We will not go for this by now.
