### ISSUE TITLE
version number in IRI of Newton and Farad

### ISSUE THREAD

**Issue by mospring** [emmo-repo/EMMO#70]
The IRI of Newton and Farad contains the version 1.0.0-alpha or 1.0.0-alpha2. This must be a mistake.

**Comment by jesper-friis** [comment]
Thank you Maja. You are very right. This is fixed in the branch 'update-units-extension' , which is a not yet merged pull request.

**Comment by jesper-friis** [comment]
Due to a long-standing issue with running time of the reasoner, the update-units-extension branch will probably never make it to master. I have there made a new pull request against 1.0.0-alpha2
