### ISSUE TITLE
Project support acknowledgements

### ISSUE THREAD

**Issue by gerhardgoldbeck** [emmo-repo/EMMO#71]
Can we please add the VIMMP, MarketPlace and OntoTrans projects to the acknowledgements. GCL used resources from these projects to contribute. Should be done for alpha-2
This work is conducted under the framework of the VIMMP project (2018-2021), that receives funding from the European Union’s Horizon 2020 Research and Innovation Programme, under Grant Agreement n. 760907
This work is conducted under the framework of the MarketPlace project (2018-2022), that receives funding from the European Union’s Horizon 2020 Research and Innovation Programme, under Grant Agreement n. 760173
This work is conducted under the framework of the OntoTrans project (2020-2024), that receives funding from the European Union’s Horizon 2020 Research and Innovation Programme, under Grant Agreement n. 862136

**Comment by jesper-friis** [comment]
A pull request against 1.0.0-alpha2 has been created. Sorry for the delay
